import hre from "hardhat";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.resolve(__dirname, "../../backend/.env");
const ACTORS_PATH = path.resolve(__dirname, "../demo-actors.json");

// Default placeholders (used if demo-actors.json is absent). Use THROWAWAY addresses.
let GUARDIANS = [
  "0x0000000000000000000000000000000000000001",
  "0x0000000000000000000000000000000000000002",
  "0x0000000000000000000000000000000000000003",
];
let BENEFICIARIES = [
  { wallet: "0x0000000000000000000000000000000000000004", bps: 10000 },
];
const INITIAL_FUNDING_ETH = "0.005"; // small symbolic inheritance for the demo payout

// If a demo cast exists, deploy with guardians/beneficiary we actually control
// (needed to demo the live confirm -> execute flip). See scripts/gen-demo-actors.js.
if (fs.existsSync(ACTORS_PATH)) {
  const a = JSON.parse(fs.readFileSync(ACTORS_PATH, "utf8"));
  GUARDIANS = a.guardians.map((g) => g.address);
  BENEFICIARIES = [{ wallet: a.beneficiary.address, bps: 10000 }];
  console.log("Using demo-actors.json for guardians + beneficiary.");
}

function setEnvVar(file, key, value) {
  let s = fs.readFileSync(file, "utf8");
  const line = `${key}=${value}`;
  if (new RegExp(`^${key}=`, "m").test(s)) s = s.replace(new RegExp(`^${key}=.*$`, "m"), line);
  else s = s.replace(/\n?$/, `\n${line}\n`);
  fs.writeFileSync(file, s);
}

async function main() {
  const c = await hre.ethers.deployContract("LastLogin", [GUARDIANS, BENEFICIARIES], {
    value: hre.ethers.parseEther(INITIAL_FUNDING_ETH),
  });
  await c.waitForDeployment();
  const addr = await c.getAddress();

  // Auto-fill CONTRACT_ADDRESS in backend/.env (resolves GitHub issue #5).
  if (fs.existsSync(ENV_PATH)) {
    setEnvVar(ENV_PATH, "CONTRACT_ADDRESS", addr);
    console.log("✔ Wrote CONTRACT_ADDRESS to backend/.env");
  } else {
    console.log("backend/.env not found — add manually:  CONTRACT_ADDRESS=" + addr);
  }

  // Persist the exact constructor args so `hardhat verify` always matches (issue #6).
  const argsPath = path.resolve(__dirname, "verify-args.cjs");
  fs.writeFileSync(
    argsPath,
    "// Auto-generated by deploy.js — constructor args for `hardhat verify`.\n" +
      `module.exports = ${JSON.stringify([GUARDIANS, BENEFICIARIES.map((b) => [b.wallet, b.bps])], null, 2)};\n`
  );

  console.log("LastLogin deployed to:", addr);
  console.log("View on Etherscan:     https://sepolia.etherscan.io/address/" + addr);
  console.log("Verify (needs ETHERSCAN_API_KEY):");
  console.log(`  npx hardhat verify --network sepolia --constructor-args scripts/verify-args.cjs ${addr}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
