// Auto-generated by deploy.js — constructor args for `hardhat verify`.
module.exports = [
  [
    "0xFCBb327f45fA541CA6dAd0C0b60a9E48eDAfD011",
    "0x0155837638f12E9aE289791f8998B0CFb9697808",
    "0xC1C28BD313Daae8fb4FfcaDAdE5E983B2C668A6d"
  ],
  [
    [
      "0x69285adF8F98A484c00062462E429201fb8c61E0",
      10000
    ]
  ]
];
